version = 0.1
[default.deploy.parameters]
stack_name = "ssai-tweeter"
s3_prefix = "ssai-tweeter"
region = "ca-central-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
disable_rollback = true
