service: aws-lambda-puppeteer

provider:
  name: aws
  runtime: nodejs14.x # nodejs14.x is the only version that works for chrome-aws-lambda
  region: us-east-1  # Change to your desired AWS region
  # Add any additional configuration here, such as IAM roles or environment variables

functions:
  fetchData:
    handler: src/index.handler
    description: Capture screenshot of a web page using Puppeteer
    timeout: 30  # Adjust timeout as needed
    memorySize: 512  # Adjust memory size as needed
    # events:
    #   - httpApi:
    #       path: /capture-screenshot
    #       method: get

plugins:
  - serverless-offline  # Optional: Enables offline testing of Lambda functions

# Add any additional configuration or resources here
