AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  Simple SAM template for running a Chromium browser inside AWS Lambda

Globals:
  Function:
    Timeout: 900

Resources:
  ArticleScrapingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Searchspaceai-twitter-bot
      CodeUri: browser-function/
      Handler: app.lambdaHandler
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      MemorySize: 1024
      Role: arn:aws:iam::637423343677:role/aws-ssai-twitter-dev-lambda
      Events:
        ArticleScrapingFunctionScheduledEvent:
          Type: Schedule
          Properties:
            Schedule: rate(1 day)

Outputs:
  ArticleScrapingFunction:
    Description: Lambda Function ARN for ArticleScrapingFunction
    Value: !GetAtt ArticleScrapingFunction.Arn
